package pl.put.cocktailrecipes.ui.theme

import androidx.compose.ui.graphics.Color


val primaryLight = Color(0xFFC4AAC0)
val onPrimaryLight = Color(0xFF563B71)
val primaryContainerLight = Color(0xFFE1C4DD)
val onPrimaryContainerLight = Color(0xFF563B71)
val secondaryLight = Color(0xFF6E528A)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFF0DBFF)
val onSecondaryContainerLight = Color(0xFF563B71)
val tertiaryLight = Color(0xFFB77289)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFF4D9FF)
val onTertiaryContainerLight = Color(0xFF5A396E)
val errorLight = Color(0xFF7D4E7D)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFD6FB)
val onErrorContainerLight = Color(0xFF633664)
val backgroundLight = Color(0xFFF4EAFF)
val onBackgroundLight = Color(0xFF1E1A20)
val surfaceLight = Color(0xFFFFF8F7)
val onSurfaceLight = Color(0xFF22191B)
val surfaceVariantLight = Color(0xFFE8E0EB)
val onSurfaceVariantLight = Color(0xFF4A454E)
val outlineLight = Color(0xFF7B757F)
val outlineVariantLight = Color(0xFFCCC4CF)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF382E30)
val inverseOnSurfaceLight = Color(0xFFFEEDEF)
val inversePrimaryLight = Color(0xFFDBB9F9)
val surfaceDimLight = Color(0xFFE7D6D8)
val surfaceBrightLight = Color(0xFFFFF8F7)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFFF0F1)
val surfaceContainerLight = Color(0xFFFBEAEC)
val surfaceContainerHighLight = Color(0xFFF5E4E6)
val surfaceContainerHighestLight = Color(0xFFEFDEE0)



val primaryDark = Color(0xB58C719B)
val onPrimaryDark = Color(0xFFF0DBFF)
val primaryContainerDark = Color(0xFF563B71)
val onPrimaryContainerDark = Color(0xFFF0DBFF)
val secondaryDark = Color(0xFFDBB9F9)
val onSecondaryDark = Color(0xFF3E2459)
val secondaryContainerDark = Color(0xFF563B71)
val onSecondaryContainerDark = Color(0xFFF0DBFF)
val tertiaryDark = Color(0xFFE0B8F6)
val onTertiaryDark = Color(0xFF422356)
val tertiaryContainerDark = Color(0xFF5A396E)
val onTertiaryContainerDark = Color(0xFFF4D9FF)
val errorDark = Color(0xFFEDB4EB)
val onErrorDark = Color(0xFF4A204C)
val errorContainerDark = Color(0xFF633664)
val onErrorContainerDark = Color(0xFFFFD6FB)
val backgroundDark = Color(0xFF43364B)
val onBackgroundDark = Color(0xFFE8E0E8)
val surfaceDark = Color(0xFF191113)
val onSurfaceDark = Color(0xFFEFDEE0)
val surfaceVariantDark = Color(0xFF4A454E)
val onSurfaceVariantDark = Color(0xFFCCC4CF)
val outlineDark = Color(0xFF958E99)
val outlineVariantDark = Color(0xFF4A454E)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFEFDEE0)
val inverseOnSurfaceDark = Color(0xFF382E30)
val inversePrimaryDark = Color(0xFF6F528A)
val surfaceDimDark = Color(0xFF191113)
val surfaceBrightDark = Color(0xFF413738)
val surfaceContainerLowestDark = Color(0xFF140C0E)
val surfaceContainerLowDark = Color(0xFF22191B)
val surfaceContainerDark = Color(0xFF261D1F)
val surfaceContainerHighDark = Color(0xFF312829)
val surfaceContainerHighestDark = Color(0xFF3C3234)






